#pragma once
const uint16_t THEME_DARK_BG_COLOR = TFT_DARKGREY;
const uint16_t THEME_DARK_HIGHLIGHT_COLOR = TFT_YELLOW;
const uint16_t THEME_DARK_FONT_COLOR = TFT_WHITE;
const uint16_t THEME_DARK_TITLE_COLOR = TFT_MAGENTA;


const uint16_t THEME_LIGHT_BG_COLOR = TFT_WHITE;
const uint16_t THEME_LIGHT_HIGHLIGHT_COLOR = TFT_MAROON;
const uint16_t THEME_LIGHT_FONT_COLOR = TFT_DARKGREY;
const uint16_t THEME_LIGHT_TITLE_COLOR = TFT_DARKGREEN;
