#pragma once
const String FIRMWARE_VERSION = "0.0.1";
const int MAX_STRING_SIZE = 64;
const int INPUT_AUTO_SWITCH_TIMEOUT = 1500;

const String PWD_RULE_1 = "rnd1";
const String PWD_RULE_2 = "rnd2";


const uint16_t THEME_DARK_BG_COLOR = TFT_DARKGREY;
const uint16_t THEME_DARK_HIGHLIGHT_COLOR = TFT_YELLOW;
const uint16_t THEME_DARK_FONT_COLOR = TFT_WHITE;
const uint16_t THEME_DARK_TITLE_COLOR = TFT_MAGENTA;


const uint16_t THEME_LIGHT_BG_COLOR = TFT_WHITE;
const uint16_t THEME_LIGHT_HIGHLIGHT_COLOR = TFT_MAROON;
const uint16_t THEME_LIGHT_FONT_COLOR = TFT_DARKGREY;
const uint16_t THEME_LIGHT_TITLE_COLOR = TFT_DARKGREEN;
